// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHLcK2whPlr2JJI6Lb8MBCjS8mc0d7iQ',
    appId: '1:1027220963414:web:a8da03c4a1b1d2258f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    databaseURL: 'https://beltei-default-rtdb.firebaseio.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-BGKGCB9H9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zBVe3DmhLcoaTbK0y58wiGXw4LgZuWM',
    appId: '1:1027220963414:android:843c333bbab7acc78f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    databaseURL: 'https://beltei-default-rtdb.firebaseio.com',
    storageBucket: 'beltei.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOHLcK2whPlr2JJI6Lb8MBCjS8mc0d7iQ',
    appId: '1:1027220963414:web:aef1a62eaa9c9e8b8f7bf7',
    messagingSenderId: '1027220963414',
    projectId: 'beltei',
    authDomain: 'beltei.firebaseapp.com',
    databaseURL: 'https://beltei-default-rtdb.firebaseio.com',
    storageBucket: 'beltei.appspot.com',
    measurementId: 'G-ZXDY91GXNP',
  );
}
